version: '3'

services:
  broker_service:
    build:
      context: .
      dockerfile: dockerfile
    image: frontend:1.0
    expose:
      - 80
    container_name: backend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend-network

networks:
  frontend-network: